-- Allow the new FEDERATION_ELECTION_MANAGER role on users.role
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check
  CHECK (role IN ('FEDERATION_ADMINISTRATOR','ASSOCIATION_MANAGER','VOTER','FEDERATION_ELECTION_MANAGER'));
